version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_service_laravel
    restart: always
    ports:
      - "3339:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
